### ISSUE TITLE
Tiêu đề báo cáo

### ISSUE THREAD

**Issue by chienbn** [hungcuongqn86/mcdt#19]
Các tiêu đề báo cáo tại xã đang không lấy đc thông tin 
#UNIT_NAME#

VĂN PHÒNG HĐND - UBND

**Comment by hungcuongqn86** [comment]
đã fix lấy tên nhưng cần chỉnh temp để kết xuất báo cáo cho xã, hiện tại vẫn kết xuất báo cáo theo huyện

**Comment by hungcuongqn86** [comment]
@chienbn

**Comment by chienbn** [comment]
Cần hoàn thiện hoàn chỉnh nội dung này trước ngày ngiệm thu
