### ISSUE TITLE
NHỮNG TAG CẦN HOÀN THÀNH GẤP ĐỂ NGHIỆM THU (GẤP GẤP GẤP)

### ISSUE THREAD

**Issue by chienbn** [hungcuongqn86/mcdt#22]
1. Báo cáo tại phường xã ra đúng thông tin, số liệu
2. Hoàn chỉnh ít nhất 3->4 thủ tục có đầy đủ in ra mẫu giấy tờ cần thiết: 
 - Chuyển nhượng
 - Đăng ký biến động
 - Chuyển mục đích
 - Cấp giấy Chứng nhận
3. Sửa lại màn hình đăng nhập chút cho đẹp hơn
4. trên huyện có báo cáo tình hình tiếp nhận giải quyết hs các xã (tag này nếu kịp thì làm k thì sẽ làm sau)

**Comment by hungcuongqn86** [comment]
Báo cáo phường xã đã được

**Comment by hungcuongqn86** [comment]
Các mẫu in cho các thủ tục chú ý ko nhầm thủ tục cấp giấy vì có 3-4 cái thủ tục cấp giấy
0302 - Chuyển nhượng
0303 - Đăng ký biến động
0304 - Chuyển mục đích
0328 - Cấp giấy chứng nhận

**Comment by hungcuongqn86** [comment]
trang đăng nhập ko sửa nhé, ko biết sửa thế nào nữa
