### ISSUE TITLE
4. Cấp GCNQSD đất

### ISSUE THREAD

**Issue by hungcuongqn86** [hungcuongqn86/mcdt#28]
- Giấy biên nhận, phiếu chuyển Tên người nộp không có: Đã có thông tin in chính xác
- Phiếu Ý kiến khu dân cư không có họ và tên ông bà chủ sử dụng đất, Nguồn gốc và thời điểm chưa cập nhật; Phần mềm chưa có mục Tình trạng tranh chấp đất đai: (a Cường làm những nội dung này nhé)
- Danh sách công khai chưa cập nhật Họ ten địa chỉ chủ sử dụng:(a Cường làm những nội dung này nhé)
- Đơn đăng ký chưa cập nhật Họ ten địa chỉ chủ sử dụng (Đã có thông tin đủ)
- Tờ khai tiền sử dụng đất chưa cập nhật họ tên, diện tích đất(a Cường làm những nội dung này nhé)
- Tờ khai lệ phía trước bạ chưa cập nhật họ tên, điạ chỉ(a Cường làm những nội dung này nhé)

**Comment by chienbn** [comment]
A cường làm tt này nhe
