### ISSUE TITLE
10. Thừa kế

### ISSUE THREAD

**Issue by hungcuongqn86** [hungcuongqn86/mcdt#34]
- Giấy biên nhận, phiếu chuyển taỊ MỤC Tên, địa chỉ, điện thoại không có  (Đã OK)
- Trang tra cứu không có thông tin người để thừa kế và người thừa kế. (a Cường sửa dùng màn hình này dùng chung cho tất cả các tt)
- Văn bản phân chia:thông tin người chết chưa đủ (Đã OK)
, mục đích thời hạn sử dụng đất HNK chưa có (khong biết cái này là cái gì)
, Mục ngoài chúng tôi ra ông, bà chưa cập nhật được  (A cường sửa chỗ này nhé)
- Phần mềm cần cập nhật thêm đơn biến động (A cường sửa chỗ này nhé)
- Tờ khai thuế TNCN thông tin người để lại thừa kế sai, mục 36c loại đất , diện tích chưa có.(A cường sửa chỗ này nhé)
- Tờ khai thuế đăng ký TNCN địa chỉ chưa cập nhật(A cường sửa chỗ này nhé)
- Tờ khai Lệ phí TB mục 1.3 loại đất thứa 2 chưa có, Mục a địa chỉ và tên tổ chức chuyển giao.(A cường sửa chỗ này nhé)

**Comment by chienbn** [comment]
Anh cường xem TT này cho em nhé, có mội số nội dung em k làm đc

**Comment by hungcuongqn86** [comment]
đất HNK là đất trồng cây hàng năm khác

**Comment by hungcuongqn86** [comment]
Trang tra cứu không có thông tin người để thừa kế và người thừa kế. (a Cường sửa dùng màn hình này dùng chung cho tất cả các tt), cái này đã fix
