### ISSUE TITLE
2. Thủ tục đăng ký biến động quyền sử dụng đất

### ISSUE THREAD

**Issue by hungcuongqn86** [hungcuongqn86/mcdt#41]
- In đơn đăng ký biến động tại mục 1 thiếu thông tin người sử dụng đất (phải ghi như trên giấy CNQSD đất như họ tên, năm sinh, CMND, cấp ngày tại…..).
Tại mục 6. Thừa câu Giấy chứng nhận QSD đất.
- Khi in biên nhận và phiếu chuyển. Thông tin người nộp không đúng (phần mềm nhập ông B nộp hồ sơ nhưng biên nhận và phiếu chuyển ghi là ông A ).

**Comment by chienbn** [comment]
Da hoan thanh
